name: test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-15-intel]
        environment: [py311, py312, py313, py314]

    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          # pixi-version: v0.22.0 don't want to hard code this!
          cache: true
          # auth-host: prefix.dev
          # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run -e ${{ matrix.environment }} test

  test_threading:
    runs-on: ubuntu-latest  # do we need to do a matrix for this?
      fail-fast: false
      matrix:
        environment: [py313, py314] # probably only need 314 now, but ??

    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
      - run: pixi run -e ${{ matrix.environment }} test_threading


